swagger: '2.0'
info:
  description: This is a simple API
  version: 1.0.0
  title: dota2-hero-vote
  # put the contact info for your development or API team
  contact:
    email: yyjazsf@live.cn

  license:
    name: MIT
    url: http://www.opensource.org/licenses/mit-license.php


# all paths will be relative to the basePath specified
# basePath: /v1

# tags are used for organizing operations
tags:
- name: admins
  description: 管理员
- name: users
  description: 普通用户
schemes:
  - http
  - https
paths:
  
  /user:
    get:
      summary: 获取用户列表
      operationId: getUserList
      parameters:
        - 
          in: query
          name: username
          type: string
      responses:
        200:
          description: ok
          schema:
            type: "array"
            items: 
              $ref: "#/definitions/HeroList"

  /user/signin:
    post:
      summary: 网站内部登陆接口
      operationId: signIn
      description: 内部的登录接口
      parameters:
      - in: body
        name: loginModel
        description: 登陆json参数
        schema:
          $ref: '#/definitions/SignInRequest'
      responses:
        200:
          description: 成功登陆
          schema:
             $ref: '#/definitions/SignInResponse'
        # 201:
        #   description: item created
        400:
          description: 输入参数无效
        # 409:
        #   description: an existing item already exists
        
  /user/signout:
    get:
      summary: 用户注销
      operationId: signOut
      parameters:
      - in: header
        name: tokenId
        required: true
        type: string
      responses:
        200:
          description: ok
          schema:
            $ref: "#/definitions/SuccessResponse"
            
  /user/signup:
    post:
      summary: 网站内部注册接口
      operationId: signUp
      description: 内部注册接口
      parameters:
      - in: body
        name: signUpModel
        description: 注册json参数
        schema:
          $ref: '#/definitions/SignUpRequest'
        
      responses:
        200:
          description: ok
          schema:
             $ref: '#/definitions/SignInResponse'
  
  /hero:
    get:
      summary: 获取英雄列表
      operationId: queryHero
      parameters:
        - 
          in: "query"
          name: "type"
          description: "英雄类型(力智敏远近)"
          type: "integer"
          format: "int32"
      responses:
        200:
          description: ok
          schema:
            type: "array"
            items:
              $ref: "#/definitions/HeroList"
  
  /hero/vote:
    post:
      summary: 投票
      operationId: vote
      parameters:
        -
          in: body
          name: voteModel
          schema:
            $ref: "#/definitions/Vote"
      responses:
        200:
          description: ok
          schema:
            type: "array"
            items:
              $ref: "#/definitions/SuccessResponse"
    
      
definitions:
    # 登录请求
  SignInRequest:
    required:
      - username
      - password
    properties:
      username:
        type: string
        description: 用户名
      password:
        type: string
        format: password
        description: 密码
      checkCode:
        type: string
        description: 验证码
        
  # 登录响应
  SignInResponse:
    required:
      - message
      - code
      - tokenId
    properties:
      code:
        type: string
      message:
        type: string
      tokenId:
        type: string 
  
  # 注册请求      
  SignUpRequest:
    required: 
      - username
      - email
      - password
    properties:
      username:
        type: string
        description: 用户名
      password:
        type: string
        format: password
        description: 密码
      email:
        type: string
        description: 邮箱
      checkCode:
        type: string
        description: 验证码  
        
  # 英雄Model
  HeroList:
    description: 英雄对象
    properties:
      name:
        type: string
        description: 英雄名字
      enName:
        type: string
        description: 英雄英雄名字
      nick:
        type: string
        description: 昵称
      type:
        type: integer
        description: 英雄类型(Strength,Agility,Intelligence)
        format: int32
      vote:
        type: integer
        format: int32
        description: 当前登录用户是否投过票
  
  # 投票请求      
  Vote:
    description: 投票操作
    properties:
      heroId:
        type: string
        description: 英雄Id
      vote:
        type: integer
        format: int32
        description: 评分
        
      
  # 通用成功响应  
  SuccessResponse:
    required:
      - message
      - code
    properties:
      code:
        type: string
        example: 200
      message:
        type: string
        example: "success"
        
  # 通用失败响应        
  ErrorResponse:
    required:
      - code
      - message
    properties:
      code:
        type: string
        example: 5000
      message:
        type: string
        example: "error"
        
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /yyjazsf/hero-vote/1.0.0
